# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'SwiftUI-OMICall-Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftUI-OMICall-Example
  # Use local development pod with Swift 6 support
  # pod 'OmiKit', :path => '../../'
  # pod 'OmiKit', '1.9.21' # Replace with the latest released version if available
  pod 'OmiKit'
end

